from tkinter import *
app = Tk()
app.title("Menu bar with colors")
app.geometry("500x300")
menubar = Menu()
red = Menu(menubar, tearoff=False, background="red")
red.add_command(red.configure(bg='red'))
yellow = Menu(menubar, tearoff=False, background="yellow")
yellow.add_command(yellow.configure(bg="yellow"))
green = Menu(menubar, tearoff=False, background="green")
green.add_command(green.configure(bg="green"))
menubar.add_cascade(label="red",menu=red)
menubar.add_cascade(label="yellow",menu=yellow)
menubar.add_cascade(label="green",menu=green)
app.config(menu=menubar)
app.mainloop()